all:
  children:
    webservers:
      hosts:
        master:
          ansible_host: 3.9.173.177
          ansible_user: cloud_user

        worker1:
          ansible_host: 13.40.87.25
          ansible_user: cloud_user

        worker2:
          ansible_host: 188.121.118.68
          ansible_user: cloud_user


          

